### ISSUE TITLE
Browser-viewable output for idempotent requests (handling requests with Accept text/text and text/html)

### ISSUE THREAD

**Issue by vsekhar** [connectrpc/connect-go#549]
**Is your feature request related to a problem? Please describe.**
It would be great to point a browser to a get-able method URL and get back something sensible. This would be a handy way to expose diagnostics that also adhere to a protocol contract so they are both human-readable and machine-scrapable.

**Describe the solution you'd like**
If connect-go receives a GET request that it can handle (i.e. to an idempotent method), with "Accept: text/plain" or "text/html", it should generate a request object for that method with default values and render the response in [text format](https://protobuf.dev/reference/protobuf/textformat-spec/) with multi-line and indented formatting.

**Describe alternatives you've considered**
I hand implemented this before discovering Connect, writing vanilla HTTP handlers that answered with protos in text format when "text/html" or "text/plain" was requested, and binary format when "application/protobuf" was requested.

Seems like an easy extension to Connect that would open up lots of easy human-readable diagnostic paths.

**Comment by timostamm** [comment]
Hey @vsekhar, are you familiar with Swagger? Responding with a UI that provides documentation and the ability to formulate and run requests can be very useful. 

How would your proposal work with request messages with required fields?

**Comment by vsekhar** [comment]
Wasn't familiar with Swagger, but looks great. Will check it out.

I was thinking it would follow whatever [GET support](https://connect.build/docs/go/get-requests-and-caching) for Connect clients does. Encode to query parameters?

My use case is for a method that takes an empty request proto, and generally required fields are discouraged, so you could also just disqualify methods with request messages containing required fields from browser fetches.

**Comment by akshayjshah** [comment]
GET support for connect doesn't encode fields to query parameters, because it's not obvious how to do so. (For example: how would you encode an array of messages?) Getting that right would be just as much work as the JSON or text encodings, and we'd need to implement it in every language.

Instead, GET support is much simpler - we just put JSON into a query parameter and return JSON . (GETs also support binary data, but that's irrelevant to your needs.) URLs look like this:

```
https://api.acme.com/acme.user.v1.UserService/GetUser?connect=v1&encoding=json&message={"id": 42}
```

Browsers handle URL-escaping the JSON payload automatically. For human-readable output in web browsers, this sseems pretty good:

* Most developers are familiar with JSON, especially on the web, whereas Protobuf text format is rarely used outside Google. It's clear how to encode complex nested structures in JSON.
* There are a million JSON-formatting browser plugins. They allow you to expand and collapse portions of the response message, which makes dealing with complex responses much nicer.

In general, JSON reuses more widely-known tools. Protobuf text output might be marginally more readable in its raw form, but it's poorly supported by developer tools. At least for now, we're going to stick with what we have and avoid built-in support for the `text/plain` Content-Type.
