### ISSUE TITLE
How to properly register a type for `ErrorDetail`

### ISSUE THREAD

**Issue by washanhanzi** [connectrpc/connect-go#632]
**Describe the bug**

The error returned from `connectrpc.com/validate` can be properly unmarshalled, but other type won't work.

The error response form `connectrpc.com/validate`
```
1)	{
    	  "@type": "type.googleapis.com/buf.validate.Violations",
    	  "violations": [
    	    {
    	      "fieldPath": "name",
    	      "constraintId": "required",
    	      "message": "value is required"
    	    }
    	  ]
    	}
```

The error response from another package:
```
ERROR:
  Code: Unavailable
  Message: overloaded: back off and retry
  Details:
  1)	{
    	  "@error": "google.rpc.RetryInfo is not recognized; see @value for raw binary message data",
    	  "@type": "type.googleapis.com/google.rpc.RetryInfo",
    	  "@value": "CgIICg=="
    	}
```

I don't know if this is a bug. If not, how can I achieve the same result like `connectrpc.com/validate`?

**To Reproduce**

https://github.com/washanhanzi/connectrpc-errordetail

**Comment by jhump** [comment]
@washanhanzi, the issue is that you aren't providing the schema for `google.rpc.RetryInfo` to the client. Your example uses `grpcurl` and you are providing it schemata via the `-protoset` arg and the output of `buf build`. Your schema _imports_ the protovalidate stuff, in order to include annotations on each field. Therefore, the schema for `buf.validate.Violations` is available in that protoset file, and the client can decode it. But your protoset file does _not_ include the schema for `google.rpc.RetryInfo`.

If your server exposes the [gRPC server reflection service](https://github.com/connectrpc/grpcreflect-go/#grpcreflect), then `grpcurl` could download the definition of that message from the server (which obviously does know about it).

Without server reflection, an option is to provide another `-protoset` flag, pointing to a file that contains the schema for that message. You can do something like this to produce such a file:
```
buf build buf.build/googleapis/googleapis --type google.rpc
```
The above filters the contents of the [buf.build/googleapis/googleapis](https://buf.build/googleapis/googleapis) module to just the `google.rpc` package (which will include all of the error detail types defined therein).

So you want to try something like so:
```
grpcurl \
    -protoset <(buf build -o -) \
    -protoset <(buf build buf.build/googleapis/googleapis --type google.rpc -o -) \
    -plaintext \
    -d '{"name": "1"}' \
    localhost:8080 greet.v1.GreetService/Greet
```

**Comment by washanhanzi** [comment]
Thank you for your detailed explanation. I will close this issue.
