### ISSUE TITLE
connect.CodeOf(nil) returns connect.CodeUnknown which is different to gRPC

### ISSUE THREAD

**Issue by stan-stately** [connectrpc/connect-go#718]
**Describe the bug**
`connect.CodeOf(nil)` returns `connect.CodeUnknown` which is different to grpc which returns `codes.OK`

**To Reproduce**

You can repro with the following test:
```

func TestCodeOf(t *testing.T) {
	assert.Equal(t, connect.CodeOf(nil), connect.CodeUnknown)
	assert.Equal(t, status.Code(nil), codes.OK)
}
```

**Additional context**
- N/A

**Comment by jhump** [comment]
Connect has no `OK` [code](https://pkg.go.dev/connectrpc.com/connect#Code). This is intentional since the code is only used to classify errors. Checking if the error is nil or not is the way to determine if an operation was okay.

This is not intended to be used in exactly the same fashion as grpc-go's API. We can clarify this further in the doc comments for [`connect.CodeOf`](https://pkg.go.dev/connectrpc.com/connect#CodeOf).

**Comment by stan-stately** [comment]
thankyou
