### ISSUE TITLE
[Question] improved errors in production project

### ISSUE THREAD

**Issue by solarhell** [connectrpc/connect-go#798]
Is there anything like [this](https://go-kratos.dev/en/docs/component/errors/) in connect-rpc world?

Currently only grpc defined error can be returned in connectrpc.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/b001f160-c9e9-4d55-bd03-40bf6419d144">

Clients need to use string compare to match the underlying error.

**Comment by timostamm** [comment]
The Connect protocol is designed so that it can be transcoded to and from the gRPC protocol. This means that we are limited to the error codes also present in gRPC.

However, Connect (and most gRPC implementations) support error details. You can arbitrary Protobuf messages to provide error details. You can find documentation [here](https://connectrpc.com/docs/web/errors#error-details), and they are also covered in the protocol spec.
